### ISSUE TITLE
Introduce a sleep before reconnecting in case connection got lost, to avoid spammy error logs

### ISSUE THREAD

**Issue by daanraman** [NVISO-BE/ee-outliers#335]

**Comment by detobel36** [comment]
Currently it is ElasticSearch library that try again to connect to database (due to parameter `retry_on_timeout` set on `True`).       
So to add timer between each connection test, two solution are possible:
- wait that ElasticSearch library implement this function
- remove this auto reconnect and manage it manually

There is maybe a possibility to fetch log and only display a small message (and not all the trace)

**Comment by detobel36** [comment]
Interesting stuff about that: https://github.com/elastic/elasticsearch-py/issues/666#issuecomment-343145564

**Comment by daanraman** [comment]
Elasticsearch reconnections are now wrapped in a 1 minute sleep cycle to avoid this issue.

Example:
```

    # Initialize Elasticsearch connection
    while not es.init_connection():
        time.sleep(60)
```

**Comment by daanraman** [comment]
Tested this in a local deployment where the connection fails - sleep is respected.
